name:                wai-rate-limit-redis
version:             0.1.0.0
github:              "mbg/wai-rate-limit"
license:             MIT
license-file:        LICENSE
author:              "Michael B. Gale"
maintainer:          "m.gale@warwick.ac.uk"
copyright:           "Copyright (c) Michael B. Gale"

category:            Security
synopsis:            "Redis backend for rate limiting as WAI middleware"
description:         "A Haskell library which implements rate limiting as WAI middleware"

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings
- LambdaCase

dependencies:
- base >= 4.8 && < 5
- bytestring >= 0.9 && < 0.11
- hedis >= 0.12 && < 1
- wai-rate-limit >= 0.1 && < 1

library:
    source-dirs: src
    ghc-options:
    - -W

tests:
    wai-rate-limit-redis-tests:
        main:                Spec.hs
        source-dirs:         test
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - wai 
        - wai-extra
        - wai-rate-limit 
        - wai-rate-limit-redis
        - http-types
        - warp
        - tasty
        - tasty-hunit
        - tasty-hedgehog
